// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "advios.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic advios::ap_const_logic_1 = sc_dt::Log_1;
const sc_lv<1> advios::ap_const_lv1_0 = "0";
const sc_lv<32> advios::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> advios::ap_const_lv32_1 = "1";
const sc_lv<1> advios::ap_const_lv1_1 = "1";
const sc_lv<2> advios::ap_const_lv2_0 = "00";
const sc_logic advios::ap_const_logic_0 = sc_dt::Log_0;
const bool advios::ap_const_boolean_1 = true;

advios::advios(sc_module_name name) : sc_module(name), mVcdFile(0) {
    grp_advios_clkDivide_fu_86 = new advios_clkDivide("grp_advios_clkDivide_fu_86");
    grp_advios_clkDivide_fu_86->ap_clk(clk);
    grp_advios_clkDivide_fu_86->ap_rst(reset);
    grp_advios_clkDivide_fu_86->oneSecPulse(grp_advios_clkDivide_fu_86_oneSecPulse);
    grp_advios_clkDivide_fu_86->oneSecPulse_ap_vld(grp_advios_clkDivide_fu_86_oneSecPulse_ap_vld);
    grp_advios_clkDivide_fu_86->advios_clkCount_i(advios_clkCount);
    grp_advios_clkDivide_fu_86->advios_clkCount_o(grp_advios_clkDivide_fu_86_advios_clkCount_o);
    grp_advios_clkDivide_fu_86->advios_clkCount_o_ap_vld(grp_advios_clkDivide_fu_86_advios_clkCount_o_ap_vld);
    grp_advios_adviosThread_fu_106 = new advios_adviosThread("grp_advios_adviosThread_fu_106");
    grp_advios_adviosThread_fu_106->ap_clk(clk);
    grp_advios_adviosThread_fu_106->ap_rst(reset);
    grp_advios_adviosThread_fu_106->ctrl(ctrl);
    grp_advios_adviosThread_fu_106->inSwitch(inSwitch);
    grp_advios_adviosThread_fu_106->outLeds(grp_advios_adviosThread_fu_106_outLeds);
    grp_advios_adviosThread_fu_106->outLeds_ap_vld(grp_advios_adviosThread_fu_106_outLeds_ap_vld);
    grp_advios_adviosThread_fu_106->oneSecPulse(grp_advios_adviosThread_fu_106_oneSecPulse);

    SC_METHOD(thread_advios_clkCount);
    dont_initialize();
    sensitive << ( clk.pos() );

    SC_METHOD(thread_oneSecPulse);
    dont_initialize();
    sensitive << ( clk.pos() );

    SC_METHOD(thread_outLeds);
    dont_initialize();
    sensitive << ( clk.pos() );

    SC_METHOD(thread_advios_ssdm_threa_1_load_fu_130_p1);

    SC_METHOD(thread_advios_ssdm_threa_load_fu_126_p1);

    SC_METHOD(thread_ap_CS_fsm);

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_grp_advios_adviosThread_fu_106_oneSecPulse);
    sensitive << ( advios_ssdm_threa_load_fu_126_p1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( oneSecPulse );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( clk.pos() );

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "advios_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, clk, "(port)clk");
    sc_trace(mVcdFile, reset, "(port)reset");
    sc_trace(mVcdFile, ctrl, "(port)ctrl");
    sc_trace(mVcdFile, inSwitch, "(port)inSwitch");
    sc_trace(mVcdFile, outLeds, "(port)outLeds");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, advios_ssdm_threa_load_fu_126_p1, "advios_ssdm_threa_load_fu_126_p1");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, grp_advios_clkDivide_fu_86_oneSecPulse, "grp_advios_clkDivide_fu_86_oneSecPulse");
    sc_trace(mVcdFile, grp_advios_clkDivide_fu_86_oneSecPulse_ap_vld, "grp_advios_clkDivide_fu_86_oneSecPulse_ap_vld");
    sc_trace(mVcdFile, grp_advios_clkDivide_fu_86_advios_clkCount_o, "grp_advios_clkDivide_fu_86_advios_clkCount_o");
    sc_trace(mVcdFile, grp_advios_clkDivide_fu_86_advios_clkCount_o_ap_vld, "grp_advios_clkDivide_fu_86_advios_clkCount_o_ap_vld");
    sc_trace(mVcdFile, grp_advios_adviosThread_fu_106_outLeds, "grp_advios_adviosThread_fu_106_outLeds");
    sc_trace(mVcdFile, grp_advios_adviosThread_fu_106_outLeds_ap_vld, "grp_advios_adviosThread_fu_106_outLeds_ap_vld");
    sc_trace(mVcdFile, grp_advios_adviosThread_fu_106_oneSecPulse, "grp_advios_adviosThread_fu_106_oneSecPulse");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, oneSecPulse, "oneSecPulse");
    sc_trace(mVcdFile, advios_clkCount, "advios_clkCount");
    sc_trace(mVcdFile, advios_ssdm_threa_1_load_fu_130_p1, "advios_ssdm_threa_1_load_fu_130_p1");
#endif

    }
    mHdltvinHandle.open("advios.hdltvin.dat");
    mHdltvoutHandle.open("advios.hdltvout.dat");
}

advios::~advios() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete grp_advios_clkDivide_fu_86;
    delete grp_advios_adviosThread_fu_106;
}

void advios::thread_advios_clkCount() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, advios_ssdm_threa_load_fu_126_p1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, advios_ssdm_threa_1_load_fu_130_p1.read()))) {
        advios_clkCount = ap_const_lv32_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_advios_clkDivide_fu_86_advios_clkCount_o_ap_vld.read())) {
        advios_clkCount = grp_advios_clkDivide_fu_86_advios_clkCount_o.read();
    }
}

void advios::thread_oneSecPulse() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, grp_advios_clkDivide_fu_86_oneSecPulse_ap_vld.read())) {
        oneSecPulse =  (sc_lv<1>) (grp_advios_clkDivide_fu_86_oneSecPulse.read());
    }
}

void advios::thread_outLeds() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, grp_advios_adviosThread_fu_106_outLeds_ap_vld.read())) {
        outLeds = grp_advios_adviosThread_fu_106_outLeds.read();
    }
}

void advios::thread_advios_ssdm_threa_1_load_fu_130_p1() {
    advios_ssdm_threa_1_load_fu_130_p1 = ap_const_lv1_0;
}

void advios::thread_advios_ssdm_threa_load_fu_126_p1() {
    advios_ssdm_threa_load_fu_126_p1 = ap_const_lv1_0;
}

void advios::thread_ap_CS_fsm() {
    ap_CS_fsm = ap_const_lv2_0;
}

void advios::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void advios::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void advios::thread_grp_advios_adviosThread_fu_106_oneSecPulse() {
    grp_advios_adviosThread_fu_106_oneSecPulse =  (sc_logic) (oneSecPulse.read()[0]);
}

void advios::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"reset\" :  \"" << reset.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ctrl\" :  \"" << ctrl.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"inSwitch\" :  \"" << inSwitch.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"outLeds\" :  \"" << outLeds.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

